name: CI Pipeline for my simple CI-CD project

on:
  push:
    branches:
      - master

jobs:
# This job will create/update docker images relevant to code changes and push images to docker hub.
  building-pushing-docker-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - uses: actions/checkout@v2
    - name: Login to Docker hub
      env:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $username -p $password       
        
    - name: Build and Push Backend Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/quote-backend01:latest -f Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/quote-backend01:latest

    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/quote-frontend01:latest -f nginx/Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/quote-frontend01:latest
 
  # Manifest updating job      
  update-manifests:
    needs: building-pushing-docker-images
    runs-on: ubuntu-latest
    steps:
    - name: checkout manifests repository
      uses: actions/checkout@v3
      with:
        repository: jbaravinda/deployment
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: manifests

    - name: Update deployment manifest
      run: |
        sed -i 's|image:.*quote-backend:.*|image: aravindad94/quote-backend:latest|' manifests/backend-deployment.yaml
        sed -i 's|image:.*quote-frontend:.*|image: aravindad94/quote-frontend:latest|' manifests/frontend-deployment.yaml
      
    - name: Commit and push changes to deployment repository
      run: |
        git config --global user.name "jbaravinda"
        git config --global user.email "jbaravindadiascis@gmail.com"
        cd manifests
        cd deployment
        git add .
        git commit -m "Update images to latest"
        git push origin master
