name: CI Pipeline for my simple CI-CD project

on:
  push:
    branches:
      - master

jobs:
  building-pushing-docker-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build and Push Backend Docker Image
      run: |
        docker build -t aravindad94/quote-backend:latest -f Dockerfile .
        # echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push aravindad94/quote-backend:latest

    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t aravindad94/quote-frontend:latest -f nginx/Dockerfile .
        docker push aravindad94/quote-frontend:latest

    - name: Update Deployment Repository
      run: |
        git clone https://github.com/jbaravinda/deployment.git
        cd deployment
        sed -i 's|image:.*quote-backend:.*|image: aravindad94/quote-backend:latest|' manifests/backend-deployment.yaml
        sed -i 's|image:.*quote-frontend:.*|image: aravindad94/quote-frontend:latest|' manifests/frontend-deployment.yaml
        git config user.name "jbaravinda"
        git config user.email "jbaravindadiascis@gmail.com"
        git add .
        git commit -m "Update images to latest"
        git push origin master
